language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  # - "lts/*"
  - "12"
# before_install:
# before_script:
script:
  - yarn verify
after_success:
  - yarn report-coverage
